name: Generate README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic

      - name: Generate README
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          import os
          import glob
          from anthropic import Anthropic

          anthropic = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

          def get_repo_structure():
              files = glob.glob('**/*', recursive=True)
              return '\n'.join(files)

          def generate_readme(repo_structure):
              prompt = f"""You are an AI assistant tasked with generating a README.md file for a GitHub repository. Here's the structure of the repository:

              {repo_structure}

              Based on this structure, generate a comprehensive README.md file. Include the following sections:
              1. Project Title
              2. Description
              3. Installation
              4. Usage
              5. Contributing
              6. License

              Make educated guesses about the project based on the file structure, but keep the content general where specifics are not obvious."""

              response = anthropic.completions.create(
                  model="claude-3-haiku-20240307",
                  max_tokens_to_sample=1000,
                  prompt=prompt
              )
              
              return response.completion

          repo_structure = get_repo_structure()
          readme_content = generate_readme(repo_structure)

          with open('README.md', 'w') as readme_file:
              readme_file.write(readme_content)

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push
