name: Generate README with Claude

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic

      - name: Generate README
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          import os
          import glob
          from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT

          anthropic = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

          # Get a list of files in the repository
          files = glob.glob('**/*', recursive=True)
          file_list = "\n".join(files)

          prompt = f"{HUMAN_PROMPT}Here's a list of files in my project:\n\n{file_list}\n\nBased on this information, generate a basic README.md file for my project. Include sections such as Project Overview and File Structure. Keep it concise.{AI_PROMPT}"

          response = anthropic.completions.create(
              model="claude-3-haiku-20240307",
              max_tokens_to_sample=1000,
              prompt=prompt
          )

          with open('README.md', 'w') as readme_file:
              readme_file.write(response.completion)

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md using Claude API" || echo "No changes to commit"
          git push
